### ISSUE TITLE
Suggestion menu appears at the bottom of a text area

### ISSUE THREAD

**Issue by taguan** [dmacfarlane/angular2-mentions#20]
![textareamention](https://cloud.githubusercontent.com/assets/1026937/20301020/06d291f8-ab22-11e6-8f43-e41b95136720.png)

The suggestion menu is displayed at the bottom of the text area (observed on Chrome on Linux Mint). This is obviously very bad if the text area is big.
I think a recent change made this happen, it wasn't behaving like that last week.

**Comment by taguan** [comment]
I suspect this commit : https://github.com/dmacfarlane/angular2-mentions/commit/c7d9c9b3202714f52f1a65cfa449da01b58a7c9e
Or this commit : https://github.com/dmacfarlane/angular2-mentions/commit/b175f3eda4a963d755c12b9c63334d6b69615358

to be responsible for this, but I have no evidence of it, the code is quite fuzzy in my opinion

**Comment by dmacfarlane** [comment]
I agree c7d9c9b is causing the issue.

It seems to be a Chrome issue, as Firefox is still displaying the menu at the correct location.
