### ISSUE TITLE
support for multiple triggers and mentions arrays

### ISSUE THREAD

**Issue by joeyfromnijmegen** [dmacfarlane/angular2-mentions#22]
Hi All,
is possible to have multiple triggers for the same input field for examples (@ and #) ? 
If yes, can someone point me to how this is done? 
if no, any pointers on how I should go about implementing it?
Thanks

**Comment by dmacfarlane** [comment]
Not currently supported. To implement it you could change the mention.directive inputs to accept a richer data structure and then update the code to trigger and search appropriately.
