### ISSUE TITLE
Autocomplete menu doesn't show up on Microsoft Edge

### ISSUE THREAD

**Issue by taguan** [dmacfarlane/angular2-mentions#23]
When typing @ on the demo application, the suggestion menu doesn't show up at all (no error on console)

Using Microsoft Edge 25  (bug clearly related to the browser)

**Comment by dmacfarlane** [comment]
It's working for me using the latest version:

Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393
