### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by Truedison** [dmacfarlane/angular2-mentions#24]
Coding in Ionic 2, 

On the Web it is working

For mobile, 
Both android and ios its not working

**Comment by shyamal890** [comment]
@Truedison Were you able to make this work with Ionic2?

**Comment by Truedison** [comment]
@shyamal890 what was really your problem ? implementation or implementation problems?

**Comment by shyamal890** [comment]
I saw your issue and was wondering if this plugin would work with Ionic2.

**Comment by Truedison** [comment]
@shyamal890 yep it worked. Unfortunately I was not the one who created the mention directive for our app. I worked with implementation of it on mobile which has to do with keycodes. Its all i can help you, just a heads up for fucking problems with key codes

**Comment by lorenzosoler** [comment]
Hello, any solved this?Thank you

**Comment by JoaquimDmt** [comment]
still not solved, angular-mentions works on web during development, but after building for mobile the users list isn't displayed on triggerchar.
