### ISSUE TITLE
[mentionSelect] firing multiple times

### ISSUE THREAD

**Issue by LukePettway** [dmacfarlane/angular2-mentions#26]
Maybe I'm doing something wrong but when I use [mentionSelect] and add a function in like this

```
[mentionSelect]="myFunction()"
```

It seems to fire when doing anything, clicking, scrolling, etc. Any idea what could be up with that?

**Comment by dmacfarlane** [comment]
Try it without the parenthesis, for example:

```
[mentionSelect]="myFunction"
```

**Comment by LukePettway** [comment]
Doh, I'll give that a shot and let you know what I find out. Thanks.

**Comment by ThangLeQuoc** [comment]
@dmacfarlane I have remove the parenthesis, but it doesn't work. Can you provide a better example ?

My implement: 
HTML: [mentionSelect] = "doSomething"
TS: doSomething (value: any){
    console.log('lol');
  }

**Comment by dmacfarlane** [comment]
See #27 for an example.

**Comment by LukePettway** [comment]
Oh, I need a return value, that would be my problem. Thanks @dmacfarlane! Closing this ticket now.
