### ISSUE TITLE
[mentionSelect], how to get the value of selected item ?

### ISSUE THREAD

**Issue by ThangLeQuoc** [dmacfarlane/angular2-mentions#27]
Hi @dmacfarlane , can you provide a clear example to use [mentionSelect] ,  I can't get the selected value of  the mention

**Comment by dmacfarlane** [comment]
In the demo app,  add this to app.component.html:

````
<h3>Mention Select</h3>
<input [mention]="items" [mentionSelect]="mentioned" class="form-control" type="text">
````

And add this to app.component.ts:

````
  mentioned(mention:string) { 
    console.log("mentioned:", mention);
    return mention.toUpperCase();
  }
````

**Comment by ThangLeQuoc** [comment]
Thank for your early response,
It has get the value successfully, but after tagged, the tagged text become undefined

Error on console :

![image](https://cloud.githubusercontent.com/assets/20574640/25948032/1ead24ba-367c-11e7-9b6d-934901075e08.png)

**Comment by dmacfarlane** [comment]
Your function needs to return the value to be inserted.

**Comment by ThangLeQuoc** [comment]
It works like an angel ! A remind for you to update the README doc. Big thanks for your support
