### ISSUE TITLE
Load items via http service (Any Roadmap / Plan) ?

### ISSUE THREAD

**Issue by erikramalho** [dmacfarlane/angular2-mentions#29]
Hi @dmacfarlane,

The component is clean and exactly what I was expecting. Could update us about your plans to develop this feature?

**Comment by erikramalho** [comment]
BTW... I've started to play around and got this (As a starting point). Does it makes sense for you?
**[mention.directive.js]**
```

MentionDirective.prototype.showSearchList = function (nativeElement) {
        var _this = this;
        if (this.searchList == null) {
            var componentFactory = this._componentResolver.resolveComponentFactory(mention_list_component_1.MentionListComponent);
            var componentRef = this._viewContainerRef.createComponent(componentFactory);
            var oReq = new XMLHttpRequest();
            oReq.open("GET", "/directory/mention?text=er", true);
            oReq.setRequestHeader('Authorization', 'Bearer ' + window.localStorage.getItem("jwt"));
            oReq.addEventListener("load", transferComplete, false);
            oReq.send();
            function transferComplete(evt) {
                this.searchList = componentRef.instance;
                var result = JSON.parse(oReq.response);
                for (var j = 0; j < result.length; j++) {
                    this.searchList.items.push(result[j].name);
                };
                this.searchList.hidden = false;
                this.searchList.position(nativeElement, this.iframe);
            }
            componentRef.instance['itemClick'].subscribe(function () {
                nativeElement.focus();
                var fakeKeydown = { "keyCode": KEY_ENTER, "wasClick": true };
                _this.keyHandler(fakeKeydown, nativeElement);
            });
        }
        else {
            this.searchList.activeIndex = 0;
            this.searchList.items = this.items;
            this.searchList.hidden = false;
            this.searchList.position(nativeElement, this.iframe);
            window.setTimeout(function () { return _this.searchList.resetScroll(); });
        }
    };
```

**Comment by dmacfarlane** [comment]
The HTTP service should be implemented in the app, outside of the mentions component. It would then be possible to pass the httpItems as an observable string array, something like this:

```
<input type="text" [mention]="httpItems | async" (change)='search($event)'>
```

The app would need to know when to trigger the search, which could be done whenever the mention prefix changes by adding the (change) output above.

Presumably the HTTP call would take the prefix return the array of matching items. This assumes the total list of items is much larger than something that could be loaded in a single HTTP call.

I'll try and get an example working soon.

**Comment by erikramalho** [comment]
Cheers @dmacfarlane! You gave such an awesome direction! I'll try something here and let you know!

**Comment by dmacfarlane** [comment]
I committed an example to the "async" branch. Take a look and let me know what you think. It needs a bit more testing before merging into master.

**Comment by erikramalho** [comment]
Awesome! I'll take a look and reply to you in one business day!

**Comment by erikramalho** [comment]
Hey @dmacfarlane, sorry to ask but I'm trying to figure out how to install a branch. I've never had to do such thing. Could you please provide the commands to install it so I could test?

**Comment by dmacfarlane** [comment]
You can download the zip from here: https://github.com/dmacfarlane/angular2-mentions/tree/async

Then you should be able to run `npm install` and `ng serve` to run the demo app.

**Comment by erikramalho** [comment]
Hi @dmacfarlane, I've played around with the async branch and got stuck to show the mention list.

1. ** My WS returns a JSON Arrar with these attributes: **
```
{
    "name": "Chris Martin",
    "username": "crismartin ",
    "image": "/medium/default_user.jpg"
}
```

2. **Your getItems(term):  example, doesn't support an object, so I've tried to do:**
```
getItems(term): Promise<string[]> {
    return this.http.get('/directory/mention?text=' + term)
      .toPromise()
      .then(data => {console.log(data); return data})
      .then( (response: any) => {
        var array: string[] = [];
        for (let user of response.json()) {
          array.push(user.name);
        }  
        return array;
      })
      .catch(this.handleError);
  }
```
3. **The list never shows up...**
I believe I'm doing something wrong in getItems. I think you should consider support an object as a http response because it's pretty usual.

Could you please advise me to solve this actual problem so I could move on with the tests?

**Comment by dmacfarlane** [comment]
It actually already supports an array of objects or strings. You should be able to see that in the console.log output when running the branch code without any changes.

By default it looks for a "label" attribute, but you can use tell it to look for a "name" attribute to match your data, for example:

````
<input [mention]="httpItems | async" [labelKey]="name" (searchTerm)='search($event)'>
````

The `string[]` type specs in app.component.ts are wrong, so I will fix those, but they shouldn't prevent it from working with objects.

**Comment by erikramalho** [comment]
So I've done the following changes: 
`httpItems: Observable<any>;
private searchTermStream = new Subject<string>();
...

 getItems(term): Promise<any> {
    return this.authHttp.get('/directory/mention?text=' + term)
      .toPromise()
      .then(data => {return data})
      .then( response => response.json())
      .catch(this.handleError);
  }
`

And changed my template for this: 
` <input [mention]="httpItems | async" [labelKey]="name" class="form-control" type="text" (searchTerm)='search($event)'>`

And I still can't load the MentionList. Is there anything missing?

**Comment by dmacfarlane** [comment]
It should be `httpItems: Observable<any[]>;` and `Promise<any[]>`

If that doesn't work, you could try adding`{{httpItems | async | json}}` to the template to see the value of `httpItems` is what you expect.

**Comment by dmacfarlane** [comment]
Please try `[labelKey]="'name'"` (with nested quotes), since it's a string.

**Comment by erikramalho** [comment]
Hey, It Worked. I've done the changes you advised above and it all worked. Here's is a screenshot.

I think we could close this thread seeing it's working. Now I'll look for bugs and/or enhancements and it will be better to open new threads for those scenarios. 

![captura de tela 2017-05-24 as 13 14 25](https://cloud.githubusercontent.com/assets/5274068/26413666/1433f73c-4083-11e7-8081-4a10787f2f91.png)

**Comment by dmacfarlane** [comment]
Sounds good to me.

**Comment by poonamOgale** [comment]
Hey @dmacfarlane I m trying to use your component, I have a service that uses the in-memory-api for the data and m using httpclient service.. i can't seem to get my data in the dropdown list.
Also, m getting a error saying "cannot bind to labelKey since it's an unknown to input" 
What might have gone wrong? Can you please help?
