### ISSUE TITLE
Have option to choose value and display

### ISSUE THREAD

**Issue by erikramalho** [dmacfarlane/angular2-mentions#30]
Hey @dmacfarlane, what do you think to implement an important feature: Once the user selects a name on the list, the component could offer an option do return a value.

Ex: My list could be:
`[{name: "Erik Ramalho", value: "erikramalho1"}]`

In the list, will show "Erik Ramalho". Once I click on it, the input will be populated with @erikramalho1. This feature is important because of most of the times, we need a unique id for mark users on the server side.

**Comment by erikramalho** [comment]
Hey @dmacfarlane any news about this thread?

**Comment by dmacfarlane** [comment]
This will be possible in the next version by using the updated `mentionSelect` function.
