### ISSUE TITLE
'labelKey' option is not working with array of objects

### ISSUE THREAD

**Issue by BaseNineStudios** [dmacfarlane/angular2-mentions#36]
Hey, your module is great, I love how it works except that I'm having a hard time using labelKey to read an array of objects for the Mention list.  I've tried a number of different ways of implementing, and it keeps throwing an error.

Here's my array:

userList:Array<any> = [
    {
      "name": "My Name 1",
      "email": "name1@email.com"
    },
 {
      "name": "My Name 2",
      "email": "name2@email.com"
    },
 {
      "name": "My Name 3",
      "email": "name3@email.com"
    }
]

and here's my template code which is throwing the error:

<textarea [(ngModel)]="myNgModel" [labelKey]="'name'" class="comments"></textarea>

Any ideas?  I would love to use this module but not reading the array of objects is a deal breaker. :(

**Comment by dmacfarlane** [comment]
Support for `labelKey` was recently added and included in version `0.5.2`. Can you confirm if that is the version you're using?

**Comment by BaseNineStudios** [comment]
Hey, thanks for the reply.  I was using 0.5.1, but I upgraded to 0.5.2 and am facing the same issue.  I'll expand a bit.  I'm running the latest version of Angular.  Here's my app.module import:

import { MentionModule } from 'angular2-mentions/mention';
imports: [
   OtherModules,
   MentionModule
]

And in my main component, I'm creating an array of objects:

userList:Array<any> = [
    {
      "username" : "user1",
      "email": "user1@domain.com",
      "name": "User One"
    },
    {
      "username" : "user2",
      "email": "user2@domain.com",
      "name": "User Two"
    },
    {
      "username" : "user3",
      "email": "user3@domain.com",
      "name": "User Three"
    },
]

And then in my html I've got a textarea:

<textarea [(ngModel)]="commentModel" [mention]="userList" [labelKey]="'name'" class="comment" ></textarea>

With that it won't load anything when I start typing the @ symbol.  However, if I change the array to the following:

userList:Array<any> = ["user1", "user2", "user3"];

The it will load "undefined" because it's looking for a label key that doesn't exist. But I'm not sure why it's not reading the key from the array of objects. Any idea?

**Comment by dmacfarlane** [comment]
Thanks for the additional detail. I've been able to reproduce the issue with `labelKey` and will work on a fix. As a workaround, if you rename/map your "name" properties to the default "label" and remove the `labelKey` from your `textarea` element, it should work.

**Comment by BaseNineStudios** [comment]
Hey, I'm happy I could help. :) 

FYI, I tried what you said and it worked!  Thanks for the tip.

**Comment by dmacfarlane** [comment]
I guess if we added an `insertKey` that would allow you to specify a different property to be inserted.

**Comment by BaseNineStudios** [comment]
That would be really cool actually.

**Comment by dmacfarlane** [comment]
The labelKey issue is fixed in version 0.6.0. Note the new `[mentionConfig]` breaking change and updated README. Will look at adding an insertKey or valueKey in future.
