### ISSUE TITLE
boostrap 4

### ISSUE THREAD

**Issue by ravtakhar** [dmacfarlane/angular2-mentions#37]
Current mentions is not working with bootstrap 4. Any plans to support?

Also consider renaming project to ngx-mentions?

Thanks for the good work btw!

**Comment by dmacfarlane** [comment]
The styles just need a minor tweak for bootstrap 4. Or is there something else that is not working?

**Comment by ravtakhar** [comment]
Just the styles. Functionality is working but the styling is funky.

**Comment by dmacfarlane** [comment]
Commit 41feceb91bc2a941733e9e6e9466efd1d7792042 should improve the styles. It will be included in the next release.

**Comment by ravtakhar** [comment]
@dmacfarlane been testing and using it throughout the week. Styling seems to be working nicely thank you!
