### ISSUE TITLE
Menu items not displaying

### ISSUE THREAD

**Issue by Anoop-Goudar** [dmacfarlane/angular2-mentions#38]
I am using this for my angular 2 application which is using angular material framework.
Followed the instructions to implement this, but menu items are NOT displaying inside the dropdown which opens on giving @ character. Please find the screenshot below.
![mention](https://user-images.githubusercontent.com/4173039/30207360-e9d3992e-94ac-11e7-8359-bdd8e5325a66.png)

**Comment by dmacfarlane** [comment]
Is this still an issue?

**Comment by Anoop-Goudar** [comment]
Yes it exists.
But if I am using inside a *ngFor then surprisingly it doesn't occur.

Cheers,
Anoop

**Comment by dmacfarlane** [comment]
Can you provide an example of the template code that is causing the issue?

**Comment by Anoop-Goudar** [comment]
Sure, by tomorrow I will post .

Cheers,
Anoop
