### ISSUE TITLE
[Mention] won't update

### ISSUE THREAD

**Issue by NicCyclePath** [dmacfarlane/angular2-mentions#40]
<textarea type="text" (searchTerm)="queryKeyword($event)" [(ngModel)]="description" style="min-width: 100%" rows="4" **[mention]="items"**></textarea>
                  
I am trying to push new values to  **"items"** but after it changed. The drop down menu becomes empty.

**Comment by dmacfarlane** [comment]
See #41. You need to use the most recent version and set items to new array.

**Comment by NicCyclePath** [comment]
Thanks @dmacfarlane  I have fixed this one already. 

Instead of "[string]", I used  "Observable<any[]>" instead.
and seting items to new array do the trick ;).
