### ISSUE TITLE
Angular 4 : How to update an array bind to [mention] after an api call

### ISSUE THREAD

**Issue by ahmedbutt2015** [dmacfarlane/angular2-mentions#41]
```
ts file :
  ngOnInit():void {
    this.items.push("temp Name")
    let __this = this
    this._userService.getAll(1).subscribe(res => {
      res.users.forEach(function (a,b) {
        __this.items.push(a)
      })
      console.log(__this.items)
    })
  }
```
.html file :

`<input type="text" [mention]="items"  >`

The array is been updated and have the data from api but the directive [mention] is bind to the old array contain values that been initialized statically at start !

**Comment by dmacfarlane** [comment]
Try the latest version just published.

**Comment by ahmedbutt2015** [comment]
I'm using  "angular2-mentions": "^0.7.0" latest but not working !

**Comment by dmacfarlane** [comment]
You will need to assign items to a new array for the change to be detected. For example:

```` 
      let newItems = [];
      res.users.forEach(function (a,b) {
        newItems.push(a);
      })
      __this.items = __this.items.concat(newItems);
````
