### ISSUE TITLE
Error Unhandled Promise rejection:

### ISSUE THREAD

**Issue by AnouarCh** [dmacfarlane/angular2-mentions#47]
polyfills.js:3 Unhandled Promise rejection: Template parse errors:
"let-" is only supported on template elements. ("
    <ng-template #defaultItemTemplate [ERROR ->]let-item="item">
      {{item[labelKey]}}
    </ng-template>
"): MentionListComponent@1:38
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
    [ERROR ->]<ng-template #defaultItemTemplate let-item="item">
      {{item[labelKey]}}
    </ng-template>
"): MentionListComponent@1:4
'ng-template' is not a known element:

I have this error please can some one help me ? when I import 
 imports: [
    HttpModule,
    MentionModule,
]
Thanks

**Comment by dmacfarlane** [comment]
What version of angular you are using? `ng-template` requires version 4.

**Comment by AnouarCh** [comment]
thanks for your response ,  I m using angular 2 with ionic 2 :/, i have to do this kind of tag " @ " , so i can't ?

Thanks

**Comment by dmacfarlane** [comment]
angular2-mentions version 0.4.4 should still work with angular version 2.

**Comment by AnouarCh** [comment]
How can i get the version 0.4.4 ? i m on angular 2.1, please ? sorry I m new , Thanks for your reponse

**Comment by dmacfarlane** [comment]
Try: `npm install --save angular2-mentions@0.4.4`

**Comment by AnouarCh** [comment]
Its works thanks ! but i have a one more little problem, I m using Ionic 2 , its works on a simple input , but in a <ion-input> when i press "@" in the input , i can't write after that?

so its works on ionic ? or i have to choose another version ? 

thanks a lot for your time.

**Comment by dmacfarlane** [comment]
I don't use Ionic, so I don't know if it works.
