### ISSUE TITLE
support for angular 5 - replace ngOutletContext with ngTemplateOutletContext

### ISSUE THREAD

**Issue by jaa1982** [dmacfarlane/angular2-mentions#51]
https://github.com/dmacfarlane/angular2-mentions/blob/b13b77bab4a7ac4edc10cf93c23b47c8e77f1b49/src/mention/mention-list.component.ts#L40

Angular v5 removes support for  `NgTemplateOutlet#ngOutletContext` in favor of `ngTemplateOutletContext` , which now results in a compile time error if included. Per docs, this has actually been deprecated since Angular 4, but did not result in a compile time error

https://github.com/angular/angular/commit/7522987

It looks like there is just one reference to ngOutletContext on the above line. If this could be replaced with ngTemplateOutletContext , we could support both Angular 4 & 5

**Comment by dmacfarlane** [comment]
Version 0.7.2 published to fix this. Thanks.
