### ISSUE TITLE
Custom listing template

### ISSUE THREAD

**Issue by Hesesses** [dmacfarlane/angular2-mentions#52]
Is it possible to customize the template shown on dropdown list?
Something like ment.io:
![image](https://user-images.githubusercontent.com/2721970/32540299-f544c290-c474-11e7-9110-651d62ad9360.png)

**Comment by delaporte** [comment]
exemple of custom template is here : https://github.com/dmacfarlane/angular2-mentions/tree/master/src/app/demo-template

**Comment by AshishTiwariMEAN** [comment]
Thank you, I have used this above code in our structure, but according to the mentioned dropdown menu not listed properly.

Please check below screen shot : 

![mentioned](https://user-images.githubusercontent.com/18064298/33010222-c448f348-cdff-11e7-90d7-e5382cd4564b.png)

Can you please suggest here, how we can improve css according to the above mentioned example.

**Comment by tanmayrajani** [comment]
It would be great if the custom template thing is mentioned in README and/or used in the demo.. just so that it's easier to find.

Thanks for making this! :clinking_glasses:
