### ISSUE TITLE
Not able to find the input text in textarea

### ISSUE THREAD

**Issue by AshishTiwariMEAN** [dmacfarlane/angular2-mentions#57]
How we can customize text area input content, like if we want some hyperlink in the text.

Please have a look below screen shot, look like that we need to customize same thing in our current application 

![screen2](https://user-images.githubusercontent.com/18064298/33058663-abb67280-ceb6-11e7-9407-e2c846b0d43c.png)
![screen1](https://user-images.githubusercontent.com/18064298/33058664-abf4317e-ceb6-11e7-8f02-dcd37693d7e8.png)

Waiting for your response......

**Comment by dmacfarlane** [comment]
Custom formatting of text within input elements is not part of this package. See #34.
