### ISSUE TITLE
Unexpected value 'MentionModule' imported by the module

### ISSUE THREAD

**Issue by alacret** [dmacfarlane/angular2-mentions#9]
Used in ionic

It does not load the directive

![screen shot 2016-10-12 at 16 35 21](https://cloud.githubusercontent.com/assets/918895/19326779/e2386dd8-9099-11e6-9034-0135bef9720d.png)
![screen shot 2016-10-12 at 16 35 36](https://cloud.githubusercontent.com/assets/918895/19326789/ecd5885c-9099-11e6-96aa-1d9b01413527.png)

**Comment by dmacfarlane** [comment]
What does your import statement look like?

Can you try with the latest angular2-mentions package from NPM?

**Comment by taguan** [comment]
Maybe you are trying to use offline compilation ?
I noticed the module is not compatible with offline compilation yet, ngc needs to be used instead of tsc
